language: android 
sudo: false
addons:
  apt:
    packages:
      - p7zip
jdk:
- oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-26
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support
before_install:
- echo -e "y" > accepting
- sdkmanager --update < accepting

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://dl.google.com/android/repository/android-ndk-r15b-linux-x86_64.zip
- unzip -q android-ndk-r15b-linux-x86_64.zip

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/Smile-DK/ygopro-scripts/archive/master.zip
- unzip -q ygopro-scripts-master.zip
- mv ygopro-scripts-master script

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/purerosefallen/ygopro-222DIY/archive/master.zip
- unzip -q ygopro-222DIY-master.zip
- cp -rf ygopro-222DIY-master/expansions/script .
- rm -rf ygopro-222DIY-master/expansions/script
- cp -rf ygopro-222DIY-master/expansions mobile/assets/data
- cp -rf ygopro-222DIY-master/ocgcore Classes
- cp -rf ygopro-222DIY-master/lflist.conf mobile/assets/data/conf

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/purerosefallen/ygopro-7210srv/archive/master.zip
- unzip -q ygopro-7210srv-master.zip
- cp -rf ygopro-7210srv-master/expansions/script .
- rm -rf ygopro-7210srv-master/expansions/script
- cp -rf ygopro-7210srv-master/expansions mobile/assets/data
- cp -rf ygopro-7210srv-master/strings.conf mobile/assets/data/conf
- cp -rf ygopro-7210srv-master/cards.cdb mobile/assets/data

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/purerosefallen/ygopro-7210srv/archive/prepics.zip
- unzip -q ygopro-7210srv-prepics.zip
- cp -rf ygopro-7210srv-prepics/expansions/pics .

- 7zr a mobile/assets/data/scripts.zip script -xr!.git* -mx=0

- cp -rf tools/Application.mk libcore/jni
- cp -rf tools/*.png mobile/src/main/res/drawable

- chmod 777 ./gradlew

script:
- cd libcore
- ./../android-ndk-r15b/ndk-build -j4
- cd ..

- ./gradlew :libcore:assembleRelease :mobile:assembleMycardRelease

before_deploy:
  - mkdir op
  - mv -f mobile/build/outputs/apk/mobile-mycard-armeabi-v7a-release.apk op/ygomobile-$TRAVIS_BRANCH-arm.apk
  - mv -f mobile/build/outputs/apk/mobile-mycard-x86-release.apk op/ygomobile-$TRAVIS_BRANCH-x86.apk

deploy:
  provider: releases
  api-key: $NANAHIRA
  file_glob: true
  file: op/*.apk
  skip_cleanup: true
  on:
    tags: true