language: android 
sudo: false
addons:
  apt:
    packages:
      - p7zip
jdk:
- oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-26
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support
before_install:
- echo -e "y" > accepting
- sdkmanager --update < accepting

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://dl.google.com/android/repository/android-ndk-r15b-linux-x86_64.zip
- unzip -q android-ndk-r15b-linux-x86_64.zip

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/Fluorohydride/ygopro-core/archive/master.zip
- unzip -q ygopro-core-master.zip
- cp -rf ygopro-core-master/* Classes/ocgcore

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/Smile-DK/ygopro-scripts/archive/master.zip
- unzip -q ygopro-scripts-master.zip
- mv ygopro-scripts-master script

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/moecube/ygopro-images/releases/download/latest/ygopro-images-zh-CN.zip
- unzip -q -d pics ygopro-images-zh-CN.zip

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/MonokuroInzanaito/ygopro-777DIY/archive/master.zip
- unzip -q ygopro-777DIY-master.zip
- cp -rf ygopro-777DIY-master/expansions/script .
- rm -rf ygopro-777DIY-master/expansions/script
- cp -rf ygopro-777DIY-master/expansions/pics .
- rm -rf ygopro-777DIY-master/expansions/pics
- cp -rf ygopro-777DIY-master/expansions mobile/assets/data
- cp -rf ygopro-777DIY-master/lflist.conf mobile/assets/data/conf

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/purerosefallen/ygopro-7210srv/raw/master/cards.cdb
- cp -rf cards.cdb mobile/assets/data
- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/purerosefallen/ygopro-7210srv/raw/master/strings.conf
- cp -rf strings.conf mobile/assets/data/conf

- rm -rf pics/*.db
- rm -rf pics/thumbnail
- 7zr a mobile/assets/data/scripts.zip script -xr!.git* -mx=0
- 7zr a mobile/assets/data/pics.zip pics -xr!.git* -mx=0

- cp -rf tools/Application.mk libcore/jni
- cp -rf tools/ic_icon.png mobile/src/main/res/drawable

- chmod 777 ./gradlew

script:
- cd libcore
- ./../android-ndk-r15b/ndk-build -j4
- cd ..

- ./gradlew :libcore:assembleRelease :mobile:assembleCoreRelease :mobile:assembleMycardRelease

- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    git config --global user.name "Smile-DK";
    git config --global user.email "2236141431@qq.com";
    git clone https://github.com/Smile-DK/ygopro-svrelease;
    cd ygopro-svrelease;
    rm -rf ygomobile-777;
    mkdir ygomobile-777;
    cp -rf ../mobile/build/outputs/apk/*.apk ygomobile-777;
    git add . -A;
    git commit -m "YGOMobile 777 Build by Travis";
    git push $SMILE/Smile-DK/ygopro-svrelease master;
  fi