language: android 
sudo: false
addons:
  apt:
    packages:
      - p7zip
jdk:
- oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-26
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support
before_install:
- echo -e "y" > accepting
- sdkmanager --update < accepting

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://dl.google.com/android/repository/android-ndk-r15b-linux-x86_64.zip
- unzip -q android-ndk-r15b-linux-x86_64.zip

- mkdir script
- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/Fluorohydride/ygopro-scripts/raw/master/constant.lua
- mv -f constant.lua script
- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/Fluorohydride/ygopro-scripts/raw/master/utility.lua
- mv -f utility.lua script

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/HuangYuNan/thcsvr/archive/master.zip
- unzip -q thcsvr-master.zip
- cp -rf thcsvr-master/ocgcore Classes
- mv -f thcsvr-master/expansions/thc.cdb cards.cdb
- cp -rf cards.cdb mobile/assets/data
- cp -rf thcsvr-master/expansions/script/*.lua script
- rm -rf thcsvr-master/expansions/script/*.lua
- cp -rf thcsvr-master/lflist.conf mobile/assets/data/conf

- rm -rf thcsvr-master/expansions/pics/thumbnail
- rm -rf thcsvr-master/expansions/pics/*.db
- mv -f thcsvr-master/expansions/pics .

- cp -rf thcsvr-master/expansions mobile/assets/data

# - 7zr a mobile/assets/data/pics.zip pics -xr!.git* -mx=0
- 7zr a mobile/assets/data/scripts.zip script -xr!.git* -mx=0

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/purerosefallen/ygopro-7210srv/raw/master/strings.conf
- mv -f strings.conf mobile/assets/data/conf

- cp -rf tools/Application.mk libcore/jni
- cp -rf tools/*.png mobile/src/main/res/drawable

- chmod 777 ./gradlew

script:
- cd libcore
- ./../android-ndk-r15b/ndk-build -j4
- cd ..

- ./gradlew :libcore:assembleRelease :mobile:assembleCoreRelease :mobile:assembleMycardRelease

- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    git config --global user.name "Smile-DK";
    git config --global user.email "2236141431@qq.com";
    git clone https://github.com/Smile-DK/ygopro-svrelease;
    cd ygopro-svrelease;
    rm -rf ygomobile-thc;
    mkdir ygomobile-thc;
    cp -rf ../mobile/build/outputs/apk/*.apk ygomobile-thc;
    git add . -A;
    git commit -m "YGOMobile THC Build by Travis";
    git push $SMILE/Smile-DK/ygopro-svrelease master;
  fi