language: android 
sudo: false
addons:
  apt:
      - p7zip
jdk:
- oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-26
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support
before_install:
- echo -e "y" > accepting
- sdkmanager --update < accepting

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://dl.google.com/android/repository/android-ndk-r15b-linux-x86_64.zip
- 7zr x android-ndk-r15b-linux-x86_64.zip

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/Smile-DK/ygopro-scripts/archive/master.zip
- 7zr x ygopro-scripts-master.zip
- mv ygopro-scripts-master script

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/purerosefallen/ygopro-222DIY/archive/master.zip
- 7zr x ygopro-222DIY-master.zip
- cp -rf ygopro-222DIY-master/expansions/script .
- rm -rf ygopro-222DIY-master/expansions/script
- cp -rf ygopro-222DIY-master/expansions mobile/assets/data
- cp -rf ygopro-222DIY-master/ocgcore Classes
- cp -rf ygopro-222DIY-master/lflist.conf mobile/assets/data/conf

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/purerosefallen/ygopro-7210srv/archive/master.zip
- 7zr x ygopro-7210srv-master.zip
- cp -rf ygopro-7210srv-master/expansions/script .
- rm -rf ygopro-7210srv-master/expansions/script
- cp -rf ygopro-7210srv-master/expansions mobile/assets/data
- cp -rf ygopro-7210srv-master/strings.conf mobile/assets/data/conf
- cp -rf ygopro-7210srv-master/cards.cdb mobile/assets/data

- 7zr a mobile/assets/data/scripts.zip script -xr!.git* -mx=0

- cp -rf tools/Application.mk libcore/jni
- cp -rf tools/ic_icon.png mobile/src/main/res/drawable

- chmod 777 ./gradlew

script:
- cd libcore
- ./../android-ndk-r15b/ndk-build -j4
- cd ..

- ./gradlew :libcore:assembleRelease :mobile:assembleCoreRelease :mobile:assembleMycardRelease

- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    git config --global user.name "Smile-DK";
    git config --global user.email "2236141431@qq.com";
    git clone https://github.com/Smile-DK/ygopro-svrelease;
    cd ygopro-svrelease;
    rm -rf ygomobile-222;
    mkdir ygomobile-222;
    cp -rf ../mobile/build/outputs/apk/*.apk ygomobile-222;
    git add . -A;
    git commit -m "YGOMobile 222 Build by Travis";
    git push $SMILE/Smile-DK/ygopro-svrelease master;
  fi