language: android 
sudo: false
addons:
  apt:
    packages:
      - imagemagick
jdk:
- oraclejdk8
android:
  update_sdk: true
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-26
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support
licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
  - 'extra-android-support-.+'
before_install:
- echo y | sdkmanager --update

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://dl.google.com/android/repository/android-ndk-r15b-linux-x86_64.zip
- unzip -q android-ndk-r15b-linux-x86_64.zip

- mkdir script
- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/Fluorohydride/ygopro-scripts/raw/master/constant.lua
- mv -f constant.lua script
- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/Fluorohydride/ygopro-scripts/raw/master/utility.lua
- mv -f utility.lua script

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/HuangYuNan/thcsvr/archive/master.zip
- unzip -q thcsvr-master.zip
- cp -rf thcsvr-master/ocgcore Classes
- mv -f thcsvr-master/expansions/thc.cdb cards.cdb
- cp -rf cards.cdb mobile/assets/data
- cp -rf thcsvr-master/expansions/script/*.lua script
- rm -rf thcsvr-master/expansions/script/*.lua
- cp -rf thcsvr-master/lflist.conf mobile/assets/data/conf

- rm -rf thcsvr-master/expansions/pics/thumbnail
- rm -rf thcsvr-master/expansions/pics/*.db
- mv -f thcsvr-master/expansions/pics .

- cp -rf thcsvr-master/expansions mobile/assets/data

- zip -q -r mobile/assets/data/pics.zip pics
- zip -q -r mobile/assets/data/scripts.zip script

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/purerosefallen/ygopro-7210srv/raw/master/strings.conf
- mv -f strings.conf mobile/assets/data/conf

- cp -rf tools/Application.mk libcore/jni
- cp -rf tools/*.png mobile/src/main/res/drawable

- chmod 777 ./gradlew

script:
- cd libcore
- ./../android-ndk-r15b/ndk-build -j8
- cd ..

- ./gradlew :libcore:assembleRelease :mobile:assembleMycardRelease

before_deploy:
  - cd libcore && ./../android-ndk-r15b/ndk-build -j8 && cd ..
  - mv -f mobile/build/outputs/apk/mobile-mycard-armeabi-v7a-release.apk op/ygomobile-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.apk

deploy:
  provider: releases
  api-key: $NANAHIRA
  file_glob: true
  file: op/*.apk
  skip_cleanup: true
  on:
    branch: thc
