language: android 
sudo: false
addons:
  apt:
    packages:
      - p7zip-full
      - imagemagick
jdk:
- oraclejdk8
android:
  update_sdk: true
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-26
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support
licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
  - 'extra-android-support-.+'
env:
- QUALITY=50 YGOCC_DATA=https://dl.dropboxusercontent.com/content_link/yM7G8Il2nzrmuQZUnbeBtprmXr74GACYYzzyy8U7HlS76murD0OKxiEyc1FDMcvX/file?dl=1

before_install:
- echo y | sdkmanager --update

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://dl.google.com/android/repository/android-ndk-r15b-linux-x86_64.zip
- unzip -q android-ndk-r15b-linux-x86_64.zip

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/Fluorohydride/ygopro-scripts/archive/master.zip
- unzip -q ygopro-scripts-master.zip
- mv -f ygopro-scripts-master script

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/moecube/ygopro-images/releases/download/latest/ygopro-images-en-US.zip
- unzip -q -d pics ygopro-images-en-US.zip

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/purerosefallen/ygopro-7210srv/raw/master/lflist.conf
- mv -f lflist.conf mobile/assets/data/conf

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/moecube/ygopro-database/raw/master/locales/en-US/strings.conf
- mv -f strings.conf mobile/assets/data/conf

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/moecube/ygopro-database/raw/master/locales/en-US/cards.cdb
- mv -f cards.cdb mobile/assets/data

- mkdir mobile/assets/data/expansions

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name $YGOCC_DATA
- 7z x Cards-QCd.7z -oygocc_data
- cp -rf ygocc_data/*.cdb mobile/assets/data/expansions
- cp -rf ygocc_data/pics .
- cp -rf ygocc_data/script .

- cd pics
- rm -rf thumbnail
- rm -rf *.db
- ls *.jpg | xargs -I {} -P 4 convert -quality $QUALITY {} {}
- cd ..

# - 7zr a mobile/assets/data/pics.zip pics -xr!.git* -mx0
# - 7zr a mobile/assets/data/scripts.zip script -xr!.git* -mx0
- zip -q -r mobile/assets/data/pics.zip pics
- zip -q -r mobile/assets/data/scripts.zip script

- cp -rf mobile/src/main/res/values/strings.xml mobile/src/main/res/values-zh

- cp -rf tools/Application.mk libcore/jni
- cp -rf tools/*.png mobile/src/main/res/drawable

- chmod 777 ./gradlew

script:
- cd libcore
- ./../android-ndk-r15b/ndk-build -j4
- cd ..

- ./gradlew :libcore:assembleRelease :mobile:assembleMycardRelease

before_deploy:
  - mkdir op
  - mv -f mobile/build/outputs/apk/mobile-mycard-armeabi-v7a-release.apk op/ygomobile-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.apk

deploy:
  provider: releases
  api-key: $NANAHIRA
  file_glob: true
  file: op/*.apk
  skip_cleanup: true
  on:
    branch: ygocc
