language: android 
sudo: false
addons:
  apt:
    packages:
    # - p7zip
      - imagemagick
jdk:
- oraclejdk8
android:
  update_sdk: true
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-26
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support
licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
  - 'extra-android-support-.+'
env:
- QUALITY=45

before_install:
- echo y | sdkmanager --update

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://dl.google.com/android/repository/android-ndk-r15b-linux-x86_64.zip
- unzip -q android-ndk-r15b-linux-x86_64.zip

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/Fluorohydride/ygopro-core/archive/master.zip
- unzip -q ygopro-core-master.zip
- cp -rf ygopro-core-master/* Classes/ocgcore

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/Smile-DK/ygopro-scripts/archive/master.zip
- unzip -q ygopro-scripts-master.zip
- mv ygopro-scripts-master script

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/moecube/ygopro-images/releases/download/latest/ygopro-images-zh-CN.zip
- unzip -q -d pics ygopro-images-zh-CN.zip

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/MonokuroInzanaito/ygopro-777DIY/archive/master.zip
- unzip -q ygopro-777DIY-master.zip
- cp -rf ygopro-777DIY-master/expansions/script .
- rm -rf ygopro-777DIY-master/expansions/script
- cp -rf ygopro-777DIY-master/expansions/pics .
- rm -rf ygopro-777DIY-master/expansions/pics
- cp -rf ygopro-777DIY-master/expansions mobile/assets/data
- cp -rf ygopro-777DIY-master/lflist.conf mobile/assets/data/conf

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/purerosefallen/ygopro-7210srv/raw/master/cards.cdb
- cp -rf cards.cdb mobile/assets/data
- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/purerosefallen/ygopro-7210srv/raw/master/strings.conf
- cp -rf strings.conf mobile/assets/data/conf

- cd pics
- rm -rf thumbnail
- rm -rf *.db
- ls *.jpg | xargs -I {} -P 4 convert -quality $QUALITY {} {}
- cd ..

# - 7zr a mobile/assets/data/pics.zip pics -xr!.git* -mx0
# - 7zr a mobile/assets/data/scripts.zip script -xr!.git* -mx0
- zip -q -r mobile/assets/data/pics.zip pics
- zip -q -r mobile/assets/data/scripts.zip script

- cp -rf tools/Application.mk libcore/jni
- cp -rf tools/*.png mobile/src/main/res/drawable

- chmod 777 ./gradlew

script:
- cd libcore
- ./../android-ndk-r15b/ndk-build -j4
- cd ..

- ./gradlew :libcore:assembleRelease :mobile:assembleMycardRelease

before_deploy:
  - mkdir op
  - mv -f mobile/build/outputs/apk/mobile-mycard-armeabi-v7a-release.apk op/ygomobile-$TRAVIS_BRANCH.apk

deploy:
  provider: releases
  api-key: $NANAHIRA
  file_glob: true
  file: op/*.apk
  skip_cleanup: true
  on:
    branch: 20ex
