version: '{build}'

environment:
  ANDROID_HOME: C:\android-sdk 
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  QUALITY: 100

cache: 
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib
  - C:\Users\appveyor\.gradle
  - C:\Users\appveyor\.android
  - .gradle
  - .idea
  - mobile\build
  - libcore\build
  - libcore\libs
  - libcore\obj
install:
  - mkdir %ANDROID_HOME%
  - curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://dl.google.com/android/repository/tools_r25.2.5-windows.zip
  - 7z x -o%ANDROID_HOME% tools_r25.2.5-windows.zip > null

  - echo y | %ANDROID_HOME%\tools\android update sdk --no-ui --all --filter "platform-tools"
  - echo y | %ANDROID_HOME%\tools\android update sdk --no-ui --all --filter "tools"
  - echo y | %ANDROID_HOME%\tools\android update sdk --no-ui --all --filter "build-tools-26.0.0"
  - echo y | %ANDROID_HOME%\tools\android update sdk --no-ui --all --filter "android-26"
  - echo y | %ANDROID_HOME%\tools\android update sdk --no-ui --all --filter "extra-google-m2repository"
  - echo y | %ANDROID_HOME%\tools\android update sdk --no-ui --all --filter "extra-android-m2repository"
  
  - cp -rf tools/licenses %ANDROID_HOME%

  - choco install imagemagick.tool
  - refreshenv
  
  - curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://dl.google.com/android/repository/android-ndk-r15b-windows-x86_64.zip
  - 7z x android-ndk-r15b-windows-x86_64.zip > null

  - curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/purerosefallen/ygopro-7210srv/raw/master/strings.conf
  - mv -f strings.conf mobile/assets/data/conf

  - mkdir script
  - curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/Fluorohydride/ygopro-scripts/raw/master/constant.lua
  - mv -f constant.lua script
  - curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/Fluorohydride/ygopro-scripts/raw/master/utility.lua
  - mv -f utility.lua script

  - curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/HuangYuNan/thcsvr/archive/master.zip
  - 7z x thcsvr-master.zip > null
  - cp -rf thcsvr-master/ocgcore Classes
  - mv -f thcsvr-master/expansions/thc.cdb cards.cdb
  - cp -rf cards.cdb mobile/assets/data
  - cp -rf thcsvr-master/expansions/script/*.lua script
  - rm -rf thcsvr-master/expansions/script/*.lua
  - cp -rf thcsvr-master/lflist.conf mobile/assets/data/conf

  - rm -rf thcsvr-master/expansions/pics/thumbnail
  - rm -rf thcsvr-master/expansions/pics/*.db
  - mv -f thcsvr-master/expansions/pics .

  - cp -rf thcsvr-master/expansions mobile/assets/data

  - rm -rf pics/thumbnail
  - rm -rf pics/*.db
  - cd pics && ls *.jpg | xargs -I {} -P 4 magick -size 177x254! -quality %QUALITY% {} {} && cd ..

  - 7z a -mx0 mobile/assets/data/pics.zip pics > null
  - 7z a -mx0 mobile/assets/data/scripts.zip script > null

  - cp -rf tools/Application.mk libcore/jni
  - cp -rf tools/*.png mobile/src/main/res/drawable

build_script:
  - cd libcore && .\..\android-ndk-r15b\ndk-build -j8 && cd ..
  - ./gradlew :libcore:assembleRelease :mobile:assembleMycardRelease

after_build:
  - find . -name *.lock -print | xargs -I {} -P 4 rm -rf {}
  - find %HOMEPATH%\.gradle -name *.lock -print | xargs -I {} -P 4 rm -rf {}
  - find %HOMEPATH%\.android -name *.lock -print | xargs -I {} -P 4 rm -rf {}
  - mv -f mobile/build/outputs/apk/mobile-mycard-armeabi-v7a-release.apk ygomobile-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_NUMBER%.apk

test: off

artifacts:
  - path: ygomobile-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_NUMBER%.apk
    name: ygomobile
