version: '{build}'
skip_tags: true

install:
  - git config --global user.name "Smile-DK"
  - git config --global user.email "2236141431@qq.com"
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://dl.google.com/android/repository/android-ndk-r15b-windows-x86_64.zip ; exit 0"
  - 7z x android-ndk-r15b-windows-x86_64.zip
  - git clone https://github.com/purerosefallen/ygopro-222DIY
  - cp -rf ygopro-222DIY/ocgcore Classes

  - rm -rf libcore
  - git clone http://git.oschina.net/keyongyu/YGOMobile
  - cp -rf YGOMobile/libcore .
  - cp -rf tools/Application.mk libcore/jni

  - cd libcore
  - ../android-ndk-r15b/ndk-build.cmd -j4
  
  - cd ..
  - cp -rf libcore/libs .
  
  - 7z a libs.7z libs -mx=9 -xr!.git*
  
  - git clone https://github.com/Smile-DK/ygopro-svrelease
  - cd ygopro-svrelease
  - rm -rf libs
  - cp -rf ../libs .
  
  - git add . -A
  - git commit -m "YGOMobile Library Compiled by Appveyor"
  - git push %Smile%Smile-DK/ygopro-svrelease master
  

build: off

after_build:

test: off

cache:
  - android-ndk-r15b-windows-x86_64.zip

artifacts:
  - path: libs.7z
    name: YGOMobile Library

branches:
  only:
    - master
